version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'tcc'
      MYSQL_USER: 'tcc'
      MYSQL_PASSWORD: 'tcc'
      MYSQL_ROOT_PASSWORD: 'tcc' # Você pode alterar esta senha conforme necessário
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: