version: '3'
services:
  postgres:
    image: postgres
    container_name: back-tcc
    # restart: always
    environment:
      POSTGRES_USER: tcc
      POSTGRES_PASSWORD: tcc
      POSTGRES_DB: tcc
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
